### PR TITLE
Combine datacollection and jsonhandler

### PR DESCRIPTION
**Pull request by carmop**
Just combining the files data_collection.py and json_handler.py since they work in conjunction with each other.

### CODE REVIEW

**Comment by carmop** [comment]
Changes made, test cases passing. Also found an old test case that test a function that was removed a long time ago, so I removed it.

**Comment by carmop** [comment]
Gonna deal with the conflicts now

**Comment by noorbuchi** [comment]
@carmop Please don't forget about the recent changes from yesterday so you will also have to merge master into you branch which might cause additional conflicts

**Comment by carmop** [comment]
@yes that's what is causing the conflicts, I am correcting it rn

**Comment by carmop** [comment]
@noorbuchi yes, I am looking into it right now

**Comment by noorbuchi** [comment]
@carmop After working on the data_colection module, I really think that we should keep the json_handler and the data_collection files separate. I think that data_collection has become very large and difficult to manage and read, so I think keeping them separate would reduce complexity. Additionally, combining the two would require significant changes to the test cases and function calls, which is not ideal especially that we are approaching the due date of this project. Please let me know what you think about this, I think that the intention behind this PR is to reduce complexity by reducing the number of files to manage, but I think it does the opposite.

**Comment by carmop** [comment]
@noorbuchi I agree. It should be done earlier in the program but now it is too late

**Pull request closed without merging**
