### PR TITLE
Add updated README file

### PR DESCRIPTION
**Pull request by schultzh**
The README is currently comprised of these sections. I will tag the user who is writing the sections accordingly. 

Table of Contents @schultzh 
About @mcnultycollin 
Installing 
Testing
Running @mcnultycollin 
Contributors @schultzh 

Testing and Installing are not currently being written. If you do not currently have a task for tomorrow, please help us complete our documentation.

### CODE REVIEW

**Comment by lussierc** [comment]
Hi all, I have added the "Made with Python" badge to the README as our project is based on Python. I have seen this badge used by other open source projects and by professors in the department so I figured it would be a useful addition. Let me know if you have any questions or comments!

**Comment by mcnultycollin** [comment]
Hi all, I made changes to the readme a few hours ago, please pull and check them out before you write anything else. Removed the section 'tests' as this didn't seem relevant and wasn't in any other readmes i could find.

**Comment by mcnultycollin** [comment]
I added to the installation and running section as well, it should be pretty close to complete now.

**Comment by noorbuchi** [comment]
@schultzh @mcnultycollin @WonjoonC I don't mean to intervene in your pull request. I just want to let you all know that the file structure has been changed significantly so updates to the structure in the README will be needed.  Specifically, we've changed the number of json files, and we are working on using temporary files for test cases to avoid having 7 different json files. The file structure has not been finalized yet but I will keep you updated with what files we end up using. Please let me know if there are any questions.

**Comment by schultzh** [comment]
Thanks @noorbuchi !! I personally don't think that the file structure should be part of the README file. I personally don't see any value that it adds to the documentation. Any thoughts @mcnultycollin ?

**Comment by mcnultycollin** [comment]
Just saw the comment about removing file structure, i'll do that now.

**Pull request merged**
