### PR TITLE
Team Assignment Record

### PR DESCRIPTION
**Pull request by koscinskic**
Documented the team structure established on last Friday's practical session.

### CODE REVIEW

**Comment by schultzh** [comment]
This information has already been documented in the project manager's repository and is now redundant. I feel like we need to keep this separate from our code base.

**Comment by koscinskic** [comment]
I believe it would be proper to keep a document where the entire team can easily find it since it's not explicitly connected to project management, but rather the whole class. It would make quick reference for team composition easier and help the PyGithub / PyDriller teams properly assess whatever functions involve specific contributors on certain branches by directly pulling text from this file.

**Comment by schultzh** [comment]
The purpose of the project manager repo is for us to dispense information to the class, and for a reference for the entire class. It is not specific to the project managers.

**Comment by koscinskic** [comment]
In that case, let's close this issue and rename that repository to something more intuitive, like Gator Cogitate Planning and include a link somewhere on Slack for everyone to have on hand. I forgot this repository even existed as it is not directly connected to Cogitate through any medium besides the organization, hence the redundant information.

**Pull request closed without merging**
