### PR TITLE
Revert "Command line interface"

### PR DESCRIPTION
**Pull request by noorbuchi**
In the case that the latest merge into master was accidental, I'm creating this PR to review the changes and make sure that the master branch is returned to the previous commit.

### CODE REVIEW

**Comment by JMilamber** [comment]
continue with the revert. This happened while I was trying to merge master into the command line interface branch to update it

**Comment by noorbuchi** [comment]
@bagashvilit I will get this PR merged very soon. Let's get one or two more approvals before doing that. Preferably from a project manager.

**Comment by MaddyKapfhammer** [comment]
I think it is safe to merge this PR now!

**Comment by noorbuchi** [comment]
@MaddyKapfhammer Ok, I will do that right now, sorry for the delay.

**Pull request merged**
