### PR TITLE
Created Basic Folder Structure

### PR DESCRIPTION
**Pull request by koscinskic**
This should serve as the template for feature integration in the coming weeks. READMEs are provided in each folder detailing the purpose of said folder and will be deleted once all features are initially integrated.

### CODE REVIEW

**Comment by koscinskic** [comment]
So I just realized that "tests" is a directory automatically prevented from being added to a commit by .gitignore. Should we rename the file, or remove the .gitignore entries? We *do* want to be pushing tests, which is what the .gitignore is preventing conceptually.

**Comment by mcnultycollin** [comment]
On that note, we will want to make sure everyone merges master into their feature branches when/if these changes go through. 

> Looks very good! I feel this is a good guiding structure for our software engineering team as we work to complete this project.
> 
> We will, however, have to continue to make sure sub-teams understand how everything fits together as we move forward. Software Architects should advise their respective sub teams in this area.

**Comment by enpuyou** [comment]
Note that #31 is implementing Travis Configurations and #37 also has implemented a CLI and a quite nice overall structure of the repo

**Comment by koscinskic** [comment]
We have discussed the issue with project management who is also handling the Travis Configuration, so there shouldn't be any conflicting structure there.
#37 lacks the correct .gitignore file and does not have the correct .py files under src that software arch agreed to implement in the integration phase of the project.
I suggest we either continue developing or merge this branch now as its purpose is to provide a standardized file structure whereas #37 is meant for the CLI.

**Comment by koscinskic** [comment]
If you refer to the [diff for the .gitignore file](https://github.com/GatorCogitate/cogitate_tool/pull/39/files), I've removed the exclusions for any directory pertinent to tests. This change is necessary (and will not cause a merge conflict since this fork is up-to-date with master) as any changes made within that folder will not be pushed to master using the .gitignore currently present.

**Comment by schultzh** [comment]
Do the changes made in pull request #42 need to be put into this pull request?

**Comment by koscinskic** [comment]
I would suggest merging this first, having #42 pull master, then reformat #42 and merge.

**Pull request merged**
