### PR TITLE
Improve Travis CI configuration

### PR DESCRIPTION
**Pull request by schultzh**
In connection to Issue #30 suggestions.

### CODE REVIEW

**Comment by schultzh** [comment]
I am running into an issue where I need to add the commands to the path. 

The error I am running into is as follows:
`Error: the command ./scripts/cover.sh (from cover) could not be found within PATH.`

If anyone knows where the command needs to go into to get into the path or can help me solve this error it would be greatly appreciated.

**Comment by stephensonc** [comment]
Is it theoretically possible that the shell script doesn't have execute access? 
In the past I have had to run a `chmod +x cover.sh` in order to let the system know that it is an executable script. 
I don't know if this will fix the issue, but it may be worth trying.

**Comment by schultzh** [comment]
@stephensonc That worked! Thanks for the suggestion!!

**Comment by stephensonc** [comment]
I can likely help to troubleshoot problems in the Travis build if that would be helpful. I set up a Travis environment in a personal project, and can probably apply some of the knowledge I gained during that process to this Travis build.

**Comment by stephensonc** [comment]
The build can be integrated with master, but as it stands right now there are linter and formatting errors present in the files that have been pushed to master. I do not think it is within the jurisdiction of this pull request to modify those files, but I am interested to know what others think on that matter.

**Comment by schultzh** [comment]
@stephensonc I think it is okay to merge this as the linting errors show that the Travis CI config itself is working because it is catching the errors. Do you agree!

**Comment by stephensonc** [comment]
@schultzh I agree with that assessment. We still need reviewers to look at this, though.

**Pull request merged**
