### PR TITLE
Building and Testing Features 1 and 2

### PR DESCRIPTION
**Pull request by lussierc**
This is a Work in Progress Pull Request. We will provide insights, updates, and take feedback for our feature.

The three main questions are team were presented with are as follows:
1. Are there team members who contribute to source code without also adding test cases?
2. Or team members who only write test cases?
3. Are there team members who break the build or contribute to unusually high code churn?

This pull request aims to answer the question: Are there team members who only write test cases?

With this, the first main feature this PR adds is a feature to determine the number/percentage of commits that a user is committing to testing. To do this, we could look at the number of commits that a user is committing to the `/testing` directory. We could then set a threshold, of say 90% for example, to determine whether or not a user is only or almost only committing to testing.

### CODE REVIEW

**Comment by lussierc** [comment]
We have implemented functionality for looking at commits to testing by one specific author or all authors.

Here is the output for running with all authors:
```
Enter the link to your chosen GitHub repository: https://github.com/lussierc/simplePerformanceExperimentsJava
Adding author, Gregory M. Kapfhammer
Adding author, clussier
Adding author, Juncheng Wu
Adding author, Lancaster Wu
Adding author, Devin Ho
Adding author, Christian Lussier
Adding author, Spencer Huang
-- Repo Authors:
Gregory M. Kapfhammer
clussier
Juncheng Wu
Lancaster Wu
Devin Ho
Christian Lussier
Spencer Huang
-- Would you like to look at (1) all authors or a (2) specific author?: 1

Gregory M. Kapfhammer 's Total commits:  17
-- Testing commits by Gregory M. Kapfhammer : 0
-- Percentage of Commits Going to Testing: 0.0 %

clussier 's Total commits:  41
-- Testing commits by clussier : 1
-- Percentage of Commits Going to Testing: 2.4390243902439024 %

Juncheng Wu 's Total commits:  33
-- Testing commits by Juncheng Wu : 2
-- Percentage of Commits Going to Testing: 6.0606060606060606 %

**Comment by enpuyou** [comment]
@lussierc Is this still a Work In Progress PR? Otherwise, we can probably start to review the contents in this PR

**Comment by lussierc** [comment]
@Cory-Wiard & I have merged the features from the `BuildingAndTesting-Feature2` into the branch for this PR, `BuildingAndTesting-Feature1`.

This PR will now serve as the standalone PR for both features 1 and 2.

**Comment by lussierc** [comment]
I would say the next steps for these two features would be to continue to refactor the code, improving its comments and structure, and to write test cases for the code.

After this, we should be prepped for class-wide code integration.

**Comment by MaddyKapfhammer** [comment]
I would like to suggest that we split this pull request into two different PRs, one for the first feature and one for the second feature. I noted that the second Testing and Building feature is passing all Travis CI checks and I believe that it can be merged directly to `master`. The first Testing and Building feature is currently receiving an error with Travis CI checks that I will review and try to fix tonight, or as soon as possible, so that this feature can merged to `master` as well.

**Pull request closed without merging**
