### PR TITLE
Remove duplicate main function and its running steps

### PR DESCRIPTION
**Pull request by noorbuchi**
This PR is intended to solve the multiple main functions issue #78  I removed the main function from `data_collection.py` along with the steps to run that module from the README file. Please let me know if any other changes are necessary before merging it.

### CODE REVIEW

**Comment by bagashvilit** [comment]
@noorbuchi These changes look good, thank you for your effort. We still have to make a little change. As you remember the customer expressed his concern about metric `TOTAL` and we decided to remove it. While I acknowledge that the purpose of this pull request is to remove the main method, because of the time limit and since the PR is already open why don't we fix that too, I think it should be a quick fix. It's also a valid argument If you think that separate PR should be opened for that.

**Comment by noorbuchi** [comment]
@bagashvilit I think you make a good point. I'm currently working on adding an additional test case but then I can remove the Total metric from the dictionary and processing functions.

**Comment by bagashvilit** [comment]
@noorbuchi It should be a quick fix, but please let me know if there is anything I can help with

**Comment by noorbuchi** [comment]
@bagashvilit  I just made the changes you requested. I also added a test case that increases the code coverage for the data processing file. Please let me know if other changes are needed. Otherwise, please approve the PR after the build checks pass. Thank you!

**Comment by noorbuchi** [comment]
@MaddyKapfhammer @bagashvilit Since this is a quick fix to our current code. Should I merge it now or wait for additional approvals, I've requested several people to review but no one commented here. Please let me know what would be best to do.

**Comment by MaddyKapfhammer** [comment]
@noorbuchi I think that this PR looks great, and also needs to be merged to `master` as soon as possible. I think that you can go ahead and merge this, especially because we do not have much time left to complete the project.

**Comment by noorbuchi** [comment]
@MaddyKapfhammer I agree. I will wait for a little bit just in case someone adds their approval, then I'll merge it.

**Pull request merged**
