### PR TITLE
Add/codecoverage

### PR DESCRIPTION
**Pull request by schultzh**
In this PR I will add the uploading of code coverage reports from Travis CI.

### CODE REVIEW

**Comment by schultzh** [comment]
This will be put on hold until Travis CI is able to fetch build logs again.

**Comment by schultzh** [comment]
I am currently having getting an `OSError: [Errno 8] Exec format error` from the `pipenv run cover` command when this builds in Travis CI. Would anyone be able to help me solve this issue by lab today?

**Comment by stephensonc** [comment]
@schultzh I believe it has something to do with the removal of `#!/bin/bash` at the top of the cover.sh script. That specifies to the OS that it is executable, and it appears that it has been removed in this PR

**Comment by schultzh** [comment]
@stephensonc Thanks! That was unintentional, I put it back in the file. I appreciate your help!

**Comment by stephensonc** [comment]
We may need to add the call to `test` back in, because the coverage script now actually fulfills its intended purpose. I had originally removed it because the cover script ran the test cases in the previous version of the Travis build

**Comment by schultzh** [comment]
Add a test script file?

**Comment by spitalnyd** [comment]
> We may need to add the call to `test` back in, because the coverage script now actually fulfills its intended purpose. I had originally removed it because the cover script ran the test cases in the previous version of the Travis build

Looks like it is trying to find the call 'test' but can find it so the coverage is ultimately failing.

**Comment by stephensonc** [comment]
If I'm recalling correctly I believe that test.sh is still in the repository and worked properly, I just removed the call to it

**Comment by schultzh** [comment]
Oh got it! Done!

**Comment by stephensonc** [comment]
@spitalnyd I am looking at the build right now and it appears to be displaying reasonable coverage statistics. Where are you seeing it being unable to find test?

**Comment by spitalnyd** [comment]
> @spitalnyd I am looking at the build right now and it appears to be displaying reasonable coverage statistics. Where are you seeing it being unable to find test?

Never mind when I looked at it quick I wasn't seeing a file for test but it was added sorry for the miss communication.

**Pull request merged**
